#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
######
###### This config file is a demonstration of streaming processing in seatunnel config
######

env {
  parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 5000
}

source {
  # This is a example source plugin **only for test and demonstrate the feature source plugin**
  RabbitMQ {
           host = "localhost"
           port = 5672
           virtual_host = "/"
           username = "user"
           password = "password"
           exchange = "myex"
           routing_key = "myqueue"
           queue_name = "myqueue"
           durable = true
           exclusive = false
           auto_delete = false
           schema = {
               fields {
               }
           }
       }
}

transform {
}

sink {
  http {
;       url = "http://localhost:15672/api/exchanges/%2F/myex/publish"
      url = "http://localhost:8801/seatunnel/test/${database_name}/${table_name}"
      routing_key = "myqueue"
      method = "POST"
      user = "user"
      password = "password"
      headers {
          token = "9e32e859ef044462a257e1fc76730066"
          db_name = "${database_name}"
          table_name = "${table_name}"
      }
      array_mode = false
      batch_size = 50
      request_interval_ms = 500
      plugin_input="fake"
  }
}